### ISSUE TITLE
Dependency is missing for mybinder

### ISSUE THREAD

**Issue by darwintree** [readthedocs-examples/example-jupyter-book#2]
A [link](https://mybinder.org/v2/gh/readthedocs-examples/example-jupyter-book/main?urlpath=tree/docs/notebooks.ipynb) to mybinder is provided on https://example-jupyter-book.readthedocs.io/notebooks.html. 

But execution will fail because dependency is missing.

![image](https://user-images.githubusercontent.com/17946284/201033261-9fdcf31e-58c9-4a30-879f-df9292315871.png)

It would be better to add dependency config file according to [mybinder's document](https://mybinder.readthedocs.io/en/latest/using/config_files.html)

**Comment by benjaoming** [comment]
Actually, matplotlib is part of the current requirements. But I can see that there are more requirements that we have perhaps missed.

**Comment by benjaoming** [comment]
And btw thanks for reporting this!

**Comment by benjaoming** [comment]
Have you managed to solve the issue locally?

**Comment by darwintree** [comment]
> Have you managed to solve the issue locally?

I didn't try it, but I think an extra `requirements.txt` should be added to root directory as mybinder don't use [.readthedocs.yaml](https://github.com/readthedocs-examples/example-jupyter-book/blob/main/.readthedocs.yaml to build the project

**Comment by benjaoming** [comment]
> A [link](https://mybinder.org/v2/gh/readthedocs-examples/example-jupyter-book/main?urlpath=tree/docs/notebooks.ipynb) to mybinder is provided on https://example-jupyter-book.readthedocs.io/notebooks.html

I didn't find the link, can you help me out?

**Comment by benjaoming** [comment]
Found it!

It seems like we can create a `.binder/requirements.txt`. However, it's not so nice to maintain the same requirements two places. These requirements also have to be maintained over time. I wonder what can be the best way forwards here.

**Comment by darwintree** [comment]
> Found it!
> 
> It seems like we can create a `.binder/requirements.txt`. However, it's not so nice to maintain the same requirements two places. These requirements also have to be maintained over time. I wonder what can be the best way forwards here.

Create a symlink might help (https://git-scm.com/docs/git-symbolic-ref).
Or add `pip install docs/requirements.txt` in `postBuild`(https://mybinder.readthedocs.io/en/latest/using/config_files.html#postbuild-run-code-after-installing-the-environment)

**Comment by benjaoming** [comment]
Maybe using `-r ../docs/requirements.txt` in `.binder/requirements.txt` can work?
