### ISSUE TITLE
How to add an API session to the book?

### ISSUE THREAD

**Issue by zoccoler** [readthedocs-examples/example-jupyter-book#9]
Hi,

Thanks for this example repository! I am new to readtehdocs, but I've used jupyter-book a few times.

I would like to know if there would be a way to add an API session to the book where the functions of a local package could be also documented based on their docstrings, similar to the [tutorial of readthedocs](https://docs.readthedocs.io/en/stable/tutorial/index.html#preparing-your-project-on-github) with the `lumachi` package.

What else would have to be modified in this repo?

Thank you for your attention!

Best,
Marcelo

**Comment by zoccoler** [comment]
Hi everyone,

I think I got it to work in my [fork](https://github.com/zoccoler/example-jupyter-book/tree/main).
Let me know if you think that would be interesting.

Best,
Marcelo

**Comment by jkingslake** [comment]
I have been trying to do the same thing, but have not managed to get it working. 

When I build clone your fork that you link to above and try to build with `jupyter-book build docs`

I get 
```
WARNING: autodoc: failed to import function 'get_random_ingredients' from module 'lumache'; the following exception was raised:
No module named 'lumache'
WARNING: autodoc: failed to import function 'get_random_ingredients_B' from module 'lumache'; the following exception was raised:
No module named 'lumache'
```
Any idea what I am doing wrong?

Any help would be much appreciated!

**Comment by jkingslake** [comment]
I managed to get a version of this working using another sphinx extension, [autodoc2](https://sphinx-autodoc2.readthedocs.io/en/latest/quickstart.html#enabling-the-extension). Autodoc2 accepts an option to define where the functions you want to document are.

[Here](https://github.com/jkingslake/example-jupyter-book/tree/main) is the example repo that implements this.  

And [here](https://jkingslake-jb-autodocs2.readthedocs.io/en/latest/api.html) is the rendered documentation. 

I think it would be really useful to include this in the example repo, as I mentioned [here](https://github.com/jupyter-book/jupyter-book/issues/2277).
